[build]
  publish = "out"
  command = "npm install && npm run build && npm run export"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NEXT_PUBLIC_API_URL = "https://bpay-app.onrender.com/api"